In [37]:
%matplotlib nbagg
%load_ext autoreload
%autoreload 2
import os
import sys
import pickle

import nltk
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

chatbot_path = "/home/bi0max/projects/tutorials/chatbot"
if chatbot_path not in sys.path:
    sys.path.append(chatbot_path)

from chatbot.config import *
from chatbot.embed import *
from chatbot import embed
from chatbot.train import *
from chatbot.predict import *
from chatbot.tokenize import *

from keras.layers import Embedding, LSTM, Input, Dense
from keras.models import Model, load_model
from keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split
from copy import deepcopy

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
# read matrix, index
embedding_matrix = pickle.load(open(PATHS["embedding_matrix"], "rb"))
word2index = pickle.load(open(PATHS["word2index"], "rb"))
index2word = pickle.load(open(PATHS["index2word"], "rb"))


In [ ]:
# load trained model
model = load_model(PATHS["model"])
# get weights of updated embedding matrix
new_embedding_matrix = model.layers[2].get_weights()[0]

In [5]:
# Compare cosine similarity of original GLOVE embedding  matrix and updated (via training of chatbot) matrix
def getv(word):
    return embedding_matrix[word2index[word]]
def getvn(word):
    return new_embedding_matrix[word2index[word]]

word1 = 'are'
word2 = 're'
sim1 = cosine_similarity(getv(word1), getv(word2))
sim2 = cosine_similarity(getvn(word1), getvn(word2))
print(f"'{word1}' and '{word2}'")
print(f"Original matrix: {sim1}")
print(f"Updated matrix: {sim2}")

'are' and 're'
Original matrix: 0.4168294637427368
Updated matrix: 0.3861987292766571


In [6]:
model, encoder_model, decoder_model = create_model(PREPROCESSING_PARAMS, HPARAMS)
model.load_weights(PATHS["model"])



In [7]:
reply("Apple is orange.", encoder_model, decoder_model, word2index, index2word, PREPROCESSING_PARAMS, b=2)

1 word: 
  1 most popular: i
  2 most popular: <UNK>

2 word: 
  1 most popular: do
  2 most popular: think

3 word: 
  1 most popular: know
  2 most popular: think

4 word: 
  1 most popular: how
  2 most popular: what

5 word: 
  1 most popular: i
  2 most popular: to

6 word: 
  1 most popular: know
  2 most popular: feel

7 word: 
  1 most popular: .
  2 most popular: it

8 word: 
  1 most popular: <EOS>
  2 most popular: i



'i do know how i know .'

In [50]:
replies = reply_beam("Hey there", encoder_model, decoder_model, word2index, index2word, PREPROCESSING_PARAMS, b=30)

First run
  1 most popular: i
  2 most popular: it
  3 most popular: <UNK>
  4 most popular: he
  5 most popular: no
  6 most popular: the
  7 most popular: yes
  8 most popular: not
  9 most popular: you
  10 most popular: they
  11 most popular: yeah
  12 most popular: that
  13 most popular: well
  14 most popular: if
  15 most popular: a
  16 most popular: is
  17 most popular: <EOS>
  18 most popular: and
  19 most popular: what
  20 most popular: do
  21 most popular: this
  22 most popular: gt
  23 most popular: nope
  24 most popular: yep
  25 most popular: why
  26 most popular: nah
  27 most popular: its
  28 most popular: but
  29 most popular: as
  30 most popular: there

[['i'], ['it'], ['<UNK>'], ['he'], ['no'], ['the'], ['yes'], ['not'], ['you'], ['they'], ['yeah'], ['that'], ['well'], ['if'], ['a'], ['is'], ['<EOS>'], ['and'], ['what'], ['do'], ['this'], ['gt'], ['nope'], ['yep'], ['why'], ['nah'], ['its'], ['but'], ['as'], ['there']]
[0.09344696 0.06251715 0.0506948  0

Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27]
(12004, 30)
[[   2   18]
 [   2   25]
 [   2    6]
 [ 220    6]
 [   1   10]
 [   4   19]
 [   7    6]
 [  13   10]
 [   8   21]
 [   9   22]
 [   2   19]
 [   2   13]
 [   4   13]
 [   8   20]
 [   1    6]
 [3623    9]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit'], ['<UNK>', ',', '<UNK>', ',', '<UNK>'], ['it', 'was', 'a', 'joke', '.'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'i'], ['<UNK>', ',', '<UNK>', ',', 'and'], ['i', 'think', 'it', 'was', 'a'], ['i', 'do', 'know', 'how', 'to'], ['it', 'was', 'a', 'joke'

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spelling', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>'], ['<UNK>

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spelling', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', 

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spelling', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>',

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spel

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<U

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>'

Run for ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>']
Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.

Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spelling', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>

Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spelling', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>

Finished predictions: [16, 4, 23, 0, 1, 2, 3, 11, 15, 5, 7, 8, 24, 27, 6, 9, 10, 21, 22, 12, 13, 28, 17, 18, 14, 25, 26, 29]
(12004, 30)
[[ 1 19]
 [ 1 20]]
[['<UNK>', '.', '<EOS>'], ['yes', '.', '<EOS>'], ['yeah', '.', '<EOS>'], ['nope', '.', '<EOS>'], ['<UNK>', '<EOS>'], ['no', '<UNK>', '.', '<EOS>'], ['i', 'do', 'know', '.', '<EOS>'], ['i', 'know', '.', '<EOS>'], ['it', '<UNK>', '.', '<EOS>'], ['he', 'is', '<UNK>', '.', '<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', '<EOS>'], ['<UNK>', '<UNK>', '<EOS>'], ['it', 'was', 'a', 'joke', '.', '<EOS>'], ['i', 'think', 'it', 'is', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', 'and', '<UNK>', '.', '<EOS>'], ['it', '<UNK>', '<EOS>'], ['<EOS>'], ['<UNK>', '.', 'newlinechar', 'newlinechar', 'edit', 'spelling', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', '.', '<EOS>'], ['<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', ',', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>', '<UNK>

In [51]:
[r for r in replies if '<UNK>' not in r]

[['yes', '.', '<EOS>'],
 ['yeah', '.', '<EOS>'],
 ['nope', '.', '<EOS>'],
 ['i', 'do', 'know', '.', '<EOS>'],
 ['i', 'know', '.', '<EOS>'],
 ['it', 'was', 'a', 'joke', '.', '<EOS>'],
 ['i', 'think', 'it', 'is', '.', '<EOS>'],
 ['<EOS>'],
 ['it', 'was', 'a', 'joke', '<EOS>'],
 ['i', 'think', 'it', 'is', '<EOS>'],
 ['yes', '<EOS>'],
 ['i', 'think', 'it', 'was', 'a', 'joke', '.', '<EOS>'],
 ['i', 'do', 'know', 'how', 'to', 'pronounce', 'it', '.', '<EOS>']]